### ISSUE TITLE
Swift 4.2 content unavailable

### ISSUE THREAD

**Issue by CELSDK** [OmniVirt/OmniVirtVRPlayer-iOS-Example#3]
Hi, I am unable to use this SDK due to error in Xcode (using swift 5.0, swift 4.2 content is unavailable).
I get: "Module compiled with Swift 4.2 cannot be imported by the Swift 5.0 compiler"

**Comment by Art2VR** [comment]
Same here. We are stuck all ways now, as testing devices running iOS 12.3 are not supported in Xcode 10.1, and 10.2 onward cannot compile my completed app. Hope you can update your SDK quickly.
